import json
import torch
import optuna
import warnings
import numpy as np
import pandas as pd
import yfinance as yf
import pandas_ta as ta
from torch import nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.mixture import GaussianMixture
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import silhouette_score
from sklearn.model_selection import TimeSeriesSplit
from datetime import datetime

warnings.filterwarnings("ignore")
DEVICE = torch.device("cpu") 

class BiLSTMAutoencoder(nn.Module):
    """Heavy Bi-Directional LSTM Autoencoder with Dropout for regularization."""
    def __init__(self, input_dim, hidden_dim, latent_dim, dropout=0.2):
        super().__init__()
        # Encoder: Bi-directional
        self.encoder = nn.LSTM(
            input_dim, hidden_dim, num_layers=2, 
            batch_first=True, bidirectional=True, dropout=dropout
        )
        # BiLSTM outputs 2 * hidden_dim
        self.fc_enc = nn.Linear(hidden_dim * 2, latent_dim)
        
        # Decoder
        self.fc_dec = nn.Linear(latent_dim, hidden_dim * 2)
        self.decoder = nn.LSTM(
            hidden_dim * 2, hidden_dim, num_layers=2, 
            batch_first=True, bidirectional=True, dropout=dropout
        )
        self.out = nn.Linear(hidden_dim * 2, input_dim)

    def forward(self, x):
        _, (h, _) = self.encoder(x)
        # Concat the final hidden states of both directions from the top layer
        h_concat = torch.cat((h[-2], h[-1]), dim=1)
        latent = self.fc_enc(h_concat)
        
        dec_in = self.fc_dec(latent).unsqueeze(1).repeat(1, x.size(1), 1)
        dec_out, _ = self.decoder(dec_in)
        reconstructed = self.out(dec_out)
        return reconstructed, latent


def fetch_and_prep_data(ticker="^NSEI"):
    """Fetch Nifty 50 and engineer advanced institutional features."""
    print("Downloading data and engineering features...")
    df = yf.download(ticker, period="max", interval="1d", auto_adjust=True)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    
    # 1. Price Action & Volatility
    df["Returns"] = np.log(df["Close"] / df["Close"].shift(1))
    df["Vol_10"] = df["Returns"].rolling(10).std() * np.sqrt(252)
    df["Vol_21"] = df["Returns"].rolling(21).std() * np.sqrt(252)
    df["Vol_63"] = df["Returns"].rolling(63).std() * np.sqrt(252)
    
    # 2. Technical Indicators (using pandas-ta)
    df.ta.rsi(length=14, append=True)
    df.ta.macd(fast=12, slow=26, signal=9, append=True)
    df.ta.atr(length=14, append=True)
    
    # Clean up column names generated by pandas_ta
    df = df.rename(columns={
        "RSI_14": "RSI", 
        "MACD_12_26_9": "MACD",
        "ATRr_14": "ATR"
    })
    
    df = df.dropna()
    features = ["Returns", "Vol_10", "Vol_21", "Vol_63", "RSI", "MACD", "ATR"]
    
    scaler = StandardScaler()
    scaled_data = scaler.fit_transform(df[features].values)
    return df, scaled_data, features


def create_sequences(data, seq_len):
    X = [data[i:(i + seq_len)] for i in range(len(data) - seq_len)]
    return np.array(X)


def run_optuna_study(scaled_data, n_trials=100):
    """Exhaustive search with TimeSeries Walk-Forward Cross Validation."""
    
    def objective(trial):
        seq_len = trial.suggest_int("seq_len", 5, 42)
        hidden_dim = trial.suggest_int("hidden_dim", 32, 128)
        latent_dim = trial.suggest_int("latent_dim", 3, 15)
        lr = trial.suggest_float("lr", 1e-4, 1e-2, log=True)
        dropout = trial.suggest_float("dropout", 0.1, 0.4)
        n_clusters = trial.suggest_int("n_clusters", 3, 6)
        
        X_seq = create_sequences(scaled_data, seq_len)
        
        # TimeSeries Walk-Forward CV (3 splits)
        tscv = TimeSeriesSplit(n_splits=3)
        cv_scores = []
        
        for train_index, val_index in tscv.split(X_seq):
            X_train = X_seq[train_index]
            X_val = X_seq[val_index]
            
            tensor_X_train = torch.tensor(X_train, dtype=torch.float32).to(DEVICE)
            tensor_X_val = torch.tensor(X_val, dtype=torch.float32).to(DEVICE)
            
            loader = DataLoader(TensorDataset(tensor_X_train), batch_size=256, shuffle=True)
            model = BiLSTMAutoencoder(scaled_data.shape[1], hidden_dim, latent_dim, dropout).to(DEVICE)
            optimizer = torch.optim.Adam(model.parameters(), lr=lr)
            criterion = nn.MSELoss()
            
            # Train briefly for hyperparam evaluation
            model.train()
            for _ in range(15):
                for batch_x, in loader:
                    optimizer.zero_grad()
                    recon, _ = model(batch_x)
                    loss = criterion(recon, batch_x)
                    loss.backward()
                    optimizer.step()
                    
            model.eval()
            with torch.no_grad():
                _, latents_val = model(tensor_X_val)
            latents_np = latents_val.cpu().numpy()
            
            try:
                gmm = GaussianMixture(n_components=n_clusters, covariance_type='full', n_init=3)
                labels = gmm.fit_predict(latents_np)
                if len(set(labels)) > 1:
                    cv_scores.append(silhouette_score(latents_np, labels))
                else:
                    cv_scores.append(-1.0)
            except:
                cv_scores.append(-1.0)
                
        return np.mean(cv_scores)

    print(f"Initiating Heavy ML Auto-Tuning ({n_trials} trials, walk-forward CV)...")
    study = optuna.create_study(direction="maximize")
    study.optimize(objective, n_trials=n_trials)
    print(f"Best CV Silhouette Score: {study.best_value:.4f}")
    print(f"Optimal Parameters: {study.best_params}")
    return study.best_params


def train_final_model(scaled_data, best_params):
    """Deep training over 100 epochs using the best discovered architecture."""
    seq_len = best_params["seq_len"]
    X_seq = create_sequences(scaled_data, seq_len)
    tensor_X = torch.tensor(X_seq, dtype=torch.float32).to(DEVICE)
    loader = DataLoader(TensorDataset(tensor_X), batch_size=128, shuffle=True)
    
    model = BiLSTMAutoencoder(
        scaled_data.shape[1], 
        best_params["hidden_dim"], 
        best_params["latent_dim"],
        best_params["dropout"]
    ).to(DEVICE)
    
    optimizer = torch.optim.Adam(model.parameters(), lr=best_params["lr"])
    criterion = nn.MSELoss()
    
    print("Training final deep network (100 epochs)...")
    model.train()
    for epoch in range(100):
        total_loss = 0
        for batch_x, in loader:
            optimizer.zero_grad()
            recon, _ = model(batch_x)
            loss = criterion(recon, batch_x)
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
            
    print(f"Final Reconstruction Loss: {total_loss/len(loader):.6f}")
            
    model.eval()
    with torch.no_grad():
        _, latents = model(tensor_X)
    latents_np = latents.cpu().numpy()
    
    # robust GMM initialization
    gmm = GaussianMixture(n_components=best_params["n_clusters"], covariance_type='full', n_init=10, random_state=42)
    labels = gmm.fit_predict(latents_np)
    probs = gmm.predict_proba(latents_np)
    
    return labels, probs, seq_len


def main():
    df, scaled_data, feature_cols = fetch_and_prep_data("^NSEI")
    
    # 100 trials will likely take 10-20 minutes on GH Actions
    best_params = run_optuna_study(scaled_data, n_trials=100)
    
    labels, probs, seq_len = train_final_model(scaled_data, best_params)
    
    df_regime = df.iloc[seq_len:].copy()
    df_regime["Regime"] = labels
    
    # Map regimes logically by Risk-Adjusted Returns (Sharpe)
    summary = []
    n_clusters = best_params["n_clusters"]
    for state in range(n_clusters):
        state_returns = df_regime[df_regime["Regime"] == state]["Returns"]
        annual_return = state_returns.mean() * 252
        annual_vol = state_returns.std() * np.sqrt(252)
        sharpe = (annual_return / annual_vol) if annual_vol != 0 else 0
        summary.append({
            "state": state, "annual_return": annual_return,
            "annual_vol": annual_vol, "sharpe": sharpe,
            "samples": len(state_returns)
        })
        
    summary_sorted = sorted(summary, key=lambda x: x["sharpe"], reverse=True)
    names = ["High_Conviction_Bull", "Steady_Uptrend", "Sideways_Consolidation", "High_Vol_Bear", "Market_Crash"]
    
    state_mapping = {s["state"]: names[i] if i < len(names) else f"Regime_{i}" for i, s in enumerate(summary_sorted)}
    
    current_regime_id = int(labels[-1])
    current_regime_name = state_mapping[current_regime_id]
    current_probs = probs[-1]
    
    output_payload = {
        "updated_at": datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC"),
        "latest_close": float(df_regime["Close"].iloc[-1]),
        "latest_date": str(df_regime.index[-1].strftime("%Y-%m-%d")),
        "ml_hyperparameters": best_params,
        "current_regime_id": current_regime_id,
        "current_regime_name": current_regime_name,
        "state_probabilities": {
            state_mapping[i]: round(float(current_probs[i]), 4)
            for i in range(n_clusters)
        },
        "regime_profiles": [
            {
                "regime_name": state_mapping[s["state"]],
                "expected_annual_return": round(float(s["annual_return"]), 4),
                "expected_annual_vol": round(float(s["annual_vol"]), 4),
                "sharpe_ratio": round(float(s["sharpe"]), 4),
                "historical_days_in_regime": s["samples"]
            }
            for s in summary_sorted
        ]
    }
    
    with open("current_regime.json", "w") as f:
        json.dump(output_payload, f, indent=2)

    df_regime["Regime_Name"] = df_regime["Regime"].map(state_mapping)
    df_regime[["Close", "Returns", "Regime", "Regime_Name"]].to_csv("regime_history.csv")
    print(f"\nModel Update Complete. Current Identified Regime: {current_regime_name}")

if __name__ == "__main__":
    main()
